spring:
  config:
    activate:
      on-profile: product
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  cloud:
    aws:
      region:
        static: ${AWS_STATIC_REGION}
      credentials:
        access-key: ${AWS_CREDENTIALS_ACCESS_KEY}
        secret-key: ${AWS_CREDENTIALS_SECRET_KEY}
      s3:
        region: ${AWS_S3_REGION}
        endpoint: ${AWS_S3_ENDPOINT}
        bucket: deepdivers
