spring:
  application:
    name: backend
  profiles:
    active: local
  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 35MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: groomcommunity@gmail.com
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
    doc-expansion : none

goorm:
  community:
    server:
      url: ${SERVER_URL}

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

token:
  secret:
    key: ${TOKEN_SECRET_KEY}
  access-token:
    expiration-time: ${TOKEN_ACCESS_EXP}
  refresh-token:
    expiration-time: ${TOKEN_REFRESH_EXP}
