spring:
  config:
    activate:
      on-profile: local
  cloud:
    aws:
      s3:
        endpoint: http://localhost:4566
        bucket: test-bucket
      region:
        static: ${AWS_STATIC_REGION}
      credentials:
        access-key: test
        secret-key: test
