spring:
  application:
    name: backend
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:prod.sql
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 35MB

goorm:
  community:
    server:
      url: http://localhost:8080

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    expiration-time: 1800000
  refresh-token:
    expiration-time: 43200000
