-- Member 테이블 INSERT 쿼리
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email1@test.com', '$2a$10$0CdWONAdJgXJkBSKRY6QbuwhTfFrffR1BGQ/2OPSOfqWR5s1Y2Eu2', 'About me 1', 0, 0, 'http://blog1.com', 'http://github.com/user1', '010-1234-0001', CURRENT_TIMESTAMP, 'http://example.com/image1.jpg', 'User1', 'user1', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email2@test.com', '$2a$10$Q/1w7ts2v2d6d/u9a/cFxe0otUYfSW5JGTCUlFBy7t6fPwzozVXA2', 'About me 2', 0, 0, 'http://blog2.com', 'http://github.com/user2', '010-1234-0002', CURRENT_TIMESTAMP, 'http://example.com/image2.jpg', 'User2', 'user2', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email3@test.com', '$2a$10$e0ccirNUURfuWtZPPGvTGuZ4ttEiGX9vGjHGW.F2Rn6GXlBCmHUPC', 'About me 3', 0, 0, 'http://blog3.com', 'http://github.com/user3', '010-1234-0003', CURRENT_TIMESTAMP, 'http://example.com/image3.jpg', 'User3', 'user3', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email4@test.com', '$2a$10$Ucm41O6/Pbwn5T0kJ5gCkeS5pCYRmWkjoDzPMeStFqWgtXFtPCsG6', 'About me 4', 0, 0, 'http://blog4.com', 'http://github.com/user4', '010-1234-0004', CURRENT_TIMESTAMP, 'http://example.com/image4.jpg', 'User4', 'user4', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email5@test.com', '$2a$10$e2QsjVC2tRJugH3NuH2LoeSUwbV69LL/YR0ZEp.tGJQ65/wq.p.eS', 'About me 5', 0, 0, 'http://blog5.com', 'http://github.com/user5', '010-1234-0005', CURRENT_TIMESTAMP, 'http://example.com/image5.jpg', 'User5', 'user5', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email6@test.com', '$2a$10$BWvofLgEPX3cW98d.fil8eLC2wyO.gTmha/Xp5xB4i3kItPglgcA.', 'About me 6', 0, 0, 'http://blog6.com', 'http://github.com/user6', '010-1234-0006', CURRENT_TIMESTAMP, 'http://example.com/image6.jpg', 'User6', 'user6', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email7@test.com', '$2a$10$/zy9uEbxlSpRSkUwumLKO.OJbq3K9U0WU1ixOUEmX3ECQPJFYW2.C', 'About me 7', 0, 0, 'http://blog7.com', 'http://github.com/user7', '010-1234-0007', CURRENT_TIMESTAMP, 'http://example.com/image7.jpg', 'User7', 'user7', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email8@test.com', '$2a$10$cUZkFfaPT5iF9I/qVy3rAujp77P.kTB5zbFvZ0QFOwHPOFEytBLvm', 'About me 8', 0, 0, 'http://blog8.com', 'http://github.com/user8', '010-1234-0008', CURRENT_TIMESTAMP, 'http://example.com/image8.jpg', 'User8', 'user8', 'NORMAL', 'UNREGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email9@test.com', '$2a$10$7sCWluVvMiLkqk7BrrYiFObdBZs4FzEZZielXNUH.FS3sjDEIOzVS', 'About me 9', 0, 0, 'http://blog9.com', 'http://github.com/user9', '010-1234-0009', CURRENT_TIMESTAMP, 'http://example.com/image9.jpg', 'User9', 'user9', 'NORMAL', 'DORMANCY', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, lower_nickname, role, status, updated_at) VALUES ('email10@test.com', '$2a$10$kL5QsZWD23lNIY8pBa1UQep.WaRgv9/cMSODJmDLt6DS/sL4jagxu', 'About me 10', 0, 0, 'http://blog10.com', 'http://github.com/user10', '010-1234-0010', CURRENT_TIMESTAMP, 'http://example.com/image10.jpg', 'User10', 'user10', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);

INSERT INTO category (title) values ('테스트');

INSERT INTO post (category_id, member_id, title, content, comment_count, like_count, view_count, status, created_at, updated_at)
VALUES (1, 1, '첫 번째 게시글', '이것은 첫 번째 게시글의 내용입니다.', 0, 0, 0, 'REGISTERED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);