-- Member 테이블 INSERT 쿼리
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 1', 0, 0, 'http://blog1.com', 'http://github.com/user1', '010-1234-0001', CURRENT_TIMESTAMP, 'http://example.com/image1.jpg', 'User1', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 2', 0, 0, 'http://blog2.com', 'http://github.com/user2', '010-1234-0002', CURRENT_TIMESTAMP, 'http://example.com/image2.jpg', 'User2', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 3', 0, 0, 'http://blog3.com', 'http://github.com/user3', '010-1234-0003', CURRENT_TIMESTAMP, 'http://example.com/image3.jpg', 'User3', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 4', 0, 0, 'http://blog4.com', 'http://github.com/user4', '010-1234-0004', CURRENT_TIMESTAMP, 'http://example.com/image4.jpg', 'User4', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 5', 0, 0, 'http://blog5.com', 'http://github.com/user5', '010-1234-0005', CURRENT_TIMESTAMP, 'http://example.com/image5.jpg', 'User5', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 6', 0, 0, 'http://blog6.com', 'http://github.com/user6', '010-1234-0006', CURRENT_TIMESTAMP, 'http://example.com/image6.jpg', 'User6', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 7', 0, 0, 'http://blog7.com', 'http://github.com/user7', '010-1234-0007', CURRENT_TIMESTAMP, 'http://example.com/image7.jpg', 'User7', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 8', 0, 0, 'http://blog8.com', 'http://github.com/user8', '010-1234-0008', CURRENT_TIMESTAMP, 'http://example.com/image8.jpg', 'User8', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 9', 0, 0, 'http://blog9.com', 'http://github.com/user9', '010-1234-0009', CURRENT_TIMESTAMP, 'http://example.com/image9.jpg', 'User9', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('About me 10', 0, 0, 'http://blog10.com', 'http://github.com/user10', '010-1234-0010', CURRENT_TIMESTAMP, 'http://example.com/image10.jpg', 'User10', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);

-- Account 테이블 INSERT 쿼리
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email1@test.com', 1, 'password1!', CURRENT_TIMESTAMP);
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email2@test.com', 2, 'password2!', CURRENT_TIMESTAMP);
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email3@test.com', 3, 'password3!', CURRENT_TIMESTAMP);
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email4@test.com', 4, 'password4!', CURRENT_TIMESTAMP);
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email5@test.com', 5, 'password5!', CURRENT_TIMESTAMP);
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email6@test.com', 6, 'password6!', CURRENT_TIMESTAMP);
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email7@test.com', 7, 'password7!', CURRENT_TIMESTAMP);
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email8@test.com', 8, 'password8!', CURRENT_TIMESTAMP);
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email9@test.com', 9, 'password9!', CURRENT_TIMESTAMP);
INSERT INTO account (created_at, email, member_id, password, updated_at) VALUES (CURRENT_TIMESTAMP, 'email10@test.com', 10, 'password10!', CURRENT_TIMESTAMP);
