-- Member 테이블 INSERT 쿼리
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email1@test.com', 'password1!', 'About me 1', 0, 0, 'http://blog1.com', 'http://github.com/user1', '010-1234-0001', CURRENT_TIMESTAMP, 'http://example.com/image1.jpg', 'User1', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email2@test.com', 'password2!', 'About me 2', 0, 0, 'http://blog2.com', 'http://github.com/user2', '010-1234-0002', CURRENT_TIMESTAMP, 'http://example.com/image2.jpg', 'User2', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email3@test.com', 'password3!', 'About me 3', 0, 0, 'http://blog3.com', 'http://github.com/user3', '010-1234-0003', CURRENT_TIMESTAMP, 'http://example.com/image3.jpg', 'User3', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email4@test.com', 'password4!', 'About me 4', 0, 0, 'http://blog4.com', 'http://github.com/user4', '010-1234-0004', CURRENT_TIMESTAMP, 'http://example.com/image4.jpg', 'User4', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email5@test.com', 'password5!', 'About me 5', 0, 0, 'http://blog5.com', 'http://github.com/user5', '010-1234-0005', CURRENT_TIMESTAMP, 'http://example.com/image5.jpg', 'User5', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email6@test.com', 'password6!', 'About me 6', 0, 0, 'http://blog6.com', 'http://github.com/user6', '010-1234-0006', CURRENT_TIMESTAMP, 'http://example.com/image6.jpg', 'User6', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email7@test.com', 'password7!', 'About me 7', 0, 0, 'http://blog7.com', 'http://github.com/user7', '010-1234-0007', CURRENT_TIMESTAMP, 'http://example.com/image7.jpg', 'User7', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email8@test.com', 'password8!', 'About me 8', 0, 0, 'http://blog8.com', 'http://github.com/user8', '010-1234-0008', CURRENT_TIMESTAMP, 'http://example.com/image8.jpg', 'User8', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email9@test.com', 'password9!', 'About me 9', 0, 0, 'http://blog9.com', 'http://github.com/user9', '010-1234-0009', CURRENT_TIMESTAMP, 'http://example.com/image9.jpg', 'User9', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
INSERT INTO member (email, password, about_me, comment_count, post_count, blog_addr, github_addr, phone_number, created_at, image_url, nickname, role, status, updated_at) VALUES ('email10@test.com', 'password10!', 'About me 10', 0, 0, 'http://blog10.com', 'http://github.com/user10', '010-1234-0010', CURRENT_TIMESTAMP, 'http://example.com/image10.jpg', 'User10', 'NORMAL', 'REGISTERED', CURRENT_TIMESTAMP);
